# Generated by Django 4.1.6 on 2023-02-24 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ean', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoArticulo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('linea', models.CharField(max_length=50)),
                ('nombre', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precioUnitario', models.IntegerField(verbose_name='Precio Unitario')),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rutina_Articulo', to='rutinas.articulo')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rutina_vehiculo', to='rutinas.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articulo_tipoArticulo', to='rutinas.tipoarticulo'),
        ),
    ]
