# Generated by Django 4.1.6 on 2023-02-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltrosSustitutos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ean', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filtrosSustitutos_tipoArticulo', to='rutinas.tipoarticulo')),
            ],
        ),
    ]
