# Generated by Django 4.1.6 on 2023-02-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_filtrossustitutos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FiltrosSustitutos',
            new_name='FiltroSustituto',
        ),
    ]
