# Generated by Django 4.1.6 on 2023-02-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoBateria',
            fields=[
                ('precioUnitario', models.IntegerField(verbose_name='Precio Unitario')),
                ('ean', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
    ]
