# Generated by Django 4.1.6 on 2023-02-24 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csa',
            fields=[
                ('documento', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoArticulo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descuento', models.IntegerField()),
                ('csa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='descuento_csa', to='descuentoCSA.csa')),
                ('tipoArticulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='descuento_tipo', to='descuentoCSA.tipoarticulo')),
            ],
        ),
    ]
