# Generated by Django 4.1.6 on 2023-02-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentoCSA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='origen',
            field=models.CharField(choices=[(1, 'REPME'), (2, 'VENTANILLA')], default=1, max_length=10),
        ),
    ]
