# Generated by Django 4.1.6 on 2023-02-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentoCSA', '0002_descuento_origen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoarticulo',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='descuento',
            name='origen',
            field=models.CharField(choices=[('Repme', 'Repme'), ('Ventanilla', 'Ventanilla')], default=1, max_length=15),
        ),
    ]
