# Generated by Django 4.1.6 on 2023-02-24 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ean', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('precioInicialUnitario', models.IntegerField()),
                ('precioFinal', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('precioDescuento', models.IntegerField()),
                ('sostenimientoPrecio', models.CharField(max_length=50)),
                ('promocionAplicada', models.CharField(max_length=50)),
                ('linea', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('cajero', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=50)),
                ('tipoDocumento', models.CharField(max_length=10)),
                ('nombreCliente', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=500)),
                ('unidadNegocio', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Identificador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sostenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.CharField(max_length=50)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sostenimiento_articulo', to='sostenimientos.articulo')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articulo_factura', to='sostenimientos.factura'),
        ),
    ]
