# Generated by Django 4.1.6 on 2023-02-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sostenimientos', '0002_sostenimiento_identificador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='sostenimiento',
            name='grupo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sostenimiento_grupo', to='sostenimientos.grupo'),
            preserve_default=False,
        ),
    ]
