# Generated by Django 4.1.6 on 2023-02-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sostenimientos', '0003_grupo_sostenimiento_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articulo_factura', to='sostenimientos.factura'),
        ),
    ]
