# Generated by Django 4.1.6 on 2023-02-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sostenimientos', '0004_alter_articulo_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articulo_factura', to='sostenimientos.factura'),
        ),
        migrations.AlterField(
            model_name='sostenimiento',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sostenimiento_grupo', to='sostenimientos.grupo'),
        ),
    ]
