# Generated by Django 4.1.6 on 2023-02-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sostenimientos', '0005_alter_articulo_factura_alter_sostenimiento_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='precioInicialUnitario',
            new_name='precioInicial',
        ),
    ]
