# Generated by Django 4.1.6 on 2023-02-24 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descuentoAceite', models.IntegerField()),
                ('descuentoColision', models.IntegerField()),
                ('descuentoCabina', models.IntegerField()),
                ('descuentoCummins', models.IntegerField()),
                ('descuentoFiltro', models.IntegerField()),
                ('descuentoLlanta', models.IntegerField()),
                ('descuentoMotor', models.IntegerField()),
                ('descuentoRepuestoGeneral', models.IntegerField()),
                ('descuentoRutina', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('documento', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('categoriaVip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vip_categoriaVip', to='descuentoVIP.categoria')),
            ],
        ),
    ]
